version: "3.4"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - /home/littlediobolic/minecraft-data:/data
    ports:
      - 19132:19132/udp
      - 25565:25565
      - 28016:28016
      - 8123:8123
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      DIFFICULTY: "normal"
      OPS: "littlediobolic"
      ENABLE_RCON: "true"
      RCON_PORT: 28016
      MAX_PLAYERS: "10"
      MEMORY: "5G"
      ALLOW_NETHER: "true"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: 12
      SEED: "BIGBONEJUICE"
      MODE: "survival"
      MOTD: "STANK MC PT. 2"
      LEVEL: "Stank 2"
      ALLOW_FLIGHT: "true"
      ICON: "https://ibb.co/DG8L85h"
