version: "3.4"
services:
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 8118:80
    volumes:
      - /home/littlediobolic/organizr/config:/config